// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Services.EntityFramework;

namespace PersonalFinanceAPI.Migrations
{
    [DbContext(typeof(PersonalFinanceContext))]
    [Migration("20220217105356_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalFinance.Models.Balance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ActBalance")
                        .HasColumnType("float");

                    b.Property<DateTime>("BalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("PersonalFinance.Models.Bank", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BankValue")
                        .HasColumnType("float");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("PersonalFinance.Models.Credit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CredCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CredDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CredValue")
                        .HasColumnType("float");

                    b.Property<string>("DebName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrevDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("PersonalFinance.Models.Debit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DebDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DebInsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DebValue")
                        .HasColumnType("float");

                    b.Property<int>("Multiplier")
                        .HasColumnType("int");

                    b.Property<double>("RemainToPay")
                        .HasColumnType("float");

                    b.Property<string>("RtFreq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RtNum")
                        .HasColumnType("float");

                    b.Property<double>("RtPaid")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Debit");
                });

            modelBuilder.Entity("PersonalFinance.Models.Deposit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DepValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PercGrow")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("PersonalFinance.Models.Expiration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExpValue")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("input_value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Expiration");
                });

            modelBuilder.Entity("PersonalFinance.Models.KnownMovement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KMNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KMValue")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KnownMovement");
                });

            modelBuilder.Entity("PersonalFinance.Models.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TicketValue")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("PersonalFinance.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TrsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrsNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrsValue")
                        .HasColumnType("float");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
