// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Services.EntityFramework;

namespace PersonalFinanceAPI.Migrations
{
    [DbContext(typeof(PersonalFinanceContext))]
    partial class PersonalFinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalFinance.Models.Balance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("ActBalance")
                        .HasColumnType("real");

                    b.Property<DateTime>("BalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("PersonalFinance.Models.Bank", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BankValue")
                        .HasColumnType("real");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("PersonalFinance.Models.Credit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CredCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CredDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CredValue")
                        .HasColumnType("real");

                    b.Property<string>("DebName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Credit");
                });

            modelBuilder.Entity("PersonalFinance.Models.Debit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DebDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DebInsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DebValue")
                        .HasColumnType("real");

                    b.Property<float>("RemainToPay")
                        .HasColumnType("real");

                    b.Property<float>("RtNum")
                        .HasColumnType("real");

                    b.Property<float>("RtPaid")
                        .HasColumnType("real");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Debit");
                });

            modelBuilder.Entity("PersonalFinance.Models.Deposit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DepValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("PercGrow")
                        .HasColumnType("real");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("PersonalFinance.Models.KnownMovement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KMNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("KMValue")
                        .HasColumnType("real");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KnownMovement");
                });

            modelBuilder.Entity("PersonalFinance.Models.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TicketValue")
                        .HasColumnType("real");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("PersonalFinance.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TrsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrsNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TrsValue")
                        .HasColumnType("real");

                    b.Property<string>("Usr_OID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
